use_frameworks!

platform :ios, '10.0'

target 'SABaseKit_Example' do
  pod 'SABaseKit', :path => '../'

  target 'SABaseKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
